volumes:
  generic-sql_server_express-db-vol:

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
      # root username would be 'sa'
      MSSQL_SA_PASSWORD: 'myStrong(!)Password'
    ports:
      - 1433:1433
    volumes:
      - generic-sql_server_express-db-vol:/var/lib/mysql
